export type VocabItem = {
    english: string;
    japanese: string;
    romaji: string;
    japaneseReading: string;
    emoji: string;
};

export const beginnerVocab: VocabItem[] = [
    {
        english: 'Yes',
        japanese: 'はい',
        romaji: 'Hai',
        japaneseReading: 'はい',
        emoji: '👍',
    },
    {
        english: 'No',
        japanese: 'いいえ',
        romaji: 'Iie',
        japaneseReading: 'いいえ',
        emoji: '👎',
    },
    {
        english: 'Hello',
        japanese: 'こんにちは',
        romaji: 'Konnichiwa',
        japaneseReading: 'こんにちは',
        emoji: '👋',
    },
    {
        english: 'Help!',
        japanese: '助けて！',
        romaji: 'tasukete!',
        japaneseReading: 'たすけて！',
        emoji: '🆘',
    },
    {
        english: 'Good morning (informal)',
        japanese: 'おはよう',
        romaji: 'Ohayou',
        japaneseReading: 'おはよう',
        emoji: '🌅',
    },
    {
        english: 'Good morning (formal)',
        japanese: 'おはようございます',
        romaji: 'Ohayou gozaimasu',
        japaneseReading: 'おはようございます',
        emoji: '🌅',
    },
    {
        english: 'Good evening',
        japanese: 'こんばんは',
        romaji: 'Konbanwa',
        japaneseReading: 'こんばんは',
        emoji: '🌆',
    },
    {
        english: 'Good night',
        japanese: 'おやすみなさい',
        romaji: 'Oyasuminasai',
        japaneseReading: 'おやすみなさい',
        emoji: '🌙',
    },
    {
        english: 'See you later (informal)',
        japanese: 'じゃあね',
        romaji: 'Jaa ne',
        japaneseReading: 'じゃあね',
        emoji: '👋',
    },
    {
        english: 'Goodbye (formal / long term)',
        japanese: 'さようなら',
        romaji: 'Sayounara',
        japaneseReading: 'さようなら',
        emoji: '👋',
    },
    {
        english: 'Thank you (informal)',
        japanese: 'ありがとう',
        romaji: 'Arigatou',
        japaneseReading: 'ありがとう',
        emoji: '🙏',
    },
    {
        english: 'Thank you (formal)',
        japanese: 'ありがとうございます',
        romaji: 'Arigatou gozaimasu',
        japaneseReading: 'ありがとうございます',
        emoji: '🙏',
    },
    {
        english: 'Excuse me / Sorry (versatile)',
        japanese: 'すみません',
        romaji: 'Sumimasen',
        japaneseReading: 'すみません',
        emoji: '🙇',
    },
    {
        english: "I'm sorry (personal)",
        japanese: 'ごめんなさい',
        romaji: 'Gomen nasai',
        japaneseReading: 'ごめんなさい',
        emoji: '🙇',
    },
    {
        english: "You're welcome",
        japanese: 'どういたしまして',
        romaji: 'Dou itashimashite',
        japaneseReading: 'どういたしまして',
        emoji: '😊',
    },
    {
        english: 'What is this?',
        japanese: 'これは何ですか？',
        romaji: 'Kore wa nan desu ka?',
        japaneseReading: 'これはなんですか？',
        emoji: '❓',
    },
    {
        english: 'How much is this?',
        japanese: 'これはいくらですか？',
        romaji: 'Kore wa ikura desu ka?',
        japaneseReading: 'これはいくらですか？',
        emoji: '💰',
    },
    {
        english: "I'm fine / I'm well",
        japanese: '元気です',
        romaji: 'Genki desu',
        japaneseReading: 'げんきです',
        emoji: '🙂',
    },
    {
        english: 'I like it',
        japanese: '好きです',
        romaji: 'Suki desu',
        japaneseReading: 'すきです',
        emoji: '❤️',
    },
    {
        english: "It's okay / No problem",
        japanese: '大丈夫です',
        romaji: 'Daijoubu desu',
        japaneseReading: 'だいじょうぶです',
        emoji: '👌',
    },
    {
        english: "It's delicious",
        japanese: '美味しいです',
        romaji: 'Oishii desu',
        japaneseReading: 'おいしいです',
        emoji: '😋',
    },
    {
        english: 'Please (when offering something)',
        japanese: 'どうぞ',
        romaji: 'douzo',
        japaneseReading: 'どうぞ',
        emoji: '🤲',
    },
    {
        english: 'Please (when asking for something)',
        japanese: 'お願いします',
        romaji: 'Onegaishimasu',
        japaneseReading: 'おねがいします',
        emoji: '🙏',
    },
    {
        english: 'I would like this, please',
        japanese: 'これをお願いします',
        romaji: 'kore wo onegaishimasu',
        japaneseReading: 'これをおねがいします',
        emoji: '👇🙏',
    },
    {
        english: 'Cheers!',
        japanese: '乾杯！',
        romaji: 'Kanpai!',
        japaneseReading: 'かんぱい！',
        emoji: '🥂',
    },
    {
        english: 'Thank you for the meal (before eating)',
        japanese: 'いただきます',
        romaji: 'Itadakimasu',
        japaneseReading: 'いただきます',
        emoji: '🍛',
    },
    {
        english: 'Thank you for the meal (after eating)',
        japanese: 'ごちそうさまでした',
        romaji: 'Gochisousama deshita',
        japaneseReading: 'ごちそうさまでした',
        emoji: '🍽️',
    },
    {
        english: 'How are you?',
        japanese: 'お元気ですか？',
        romaji: 'Ogenki desu ka?',
        japaneseReading: 'おげんきですか？',
        emoji: '🫵🤔',
    },
    {
        english: 'What is your name?',
        japanese: 'お名前は何ですか？',
        romaji: 'onamae wa nan desu ka?',
        japaneseReading: 'おなまえはなんですか？',
        emoji: '👤❓',
    },
    {
        english: 'My name is...',
        japanese: '私の名前は...です',
        romaji: 'Watashi no namae wa ... desu',
        japaneseReading: 'わたしのなまえは...です',
        emoji: '👤',
    },
    {
        english: 'Where is the bathroom?',
        japanese: 'トイレはどこですか？',
        romaji: 'Toire wa doko desu ka?',
        japaneseReading: 'トイレはどこですか？',
        emoji: '🚻',
    },
    {
        english: "I don't understand",
        japanese: 'わかりません',
        romaji: 'Wakarimasen',
        japaneseReading: 'わかりません',
        emoji: '😵‍💫',
    },
    {
        english: 'Please say it again',
        japanese: 'もう一度言ってください',
        romaji: 'Mou ichido itte kudasai',
        japaneseReading: 'もういちどいってください',
        emoji: '🗣️🔁',
    },
    {
        english: 'Do you speak English?',
        japanese: '英語を話せますか？',
        romaji: 'Eigo o hanasemasu ka?',
        japaneseReading: 'えいごをはなせますか？',
        emoji: '🗣️🇬🇧',
    },
    {
        english: 'Nice to meet you',
        japanese: 'はじめまして',
        romaji: 'Hajimemashite',
        japaneseReading: 'はじめまして',
        emoji: '🤝',
    },
    {
        english: 'I can speak a little Japanese',
        japanese: '日本語が少し話せます',
        romaji: 'Nihongo ga sukoshi hanasemasu',
        japaneseReading: 'にほんごがすこしはなせます',
        emoji: '🗣️🇯🇵',
    },
    {
        english: 'Pleased to meet you (formal / sets future relationship)',
        japanese: 'よろしくお願いします',
        romaji: 'Yoroshiku onegaishimasu',
        japaneseReading: 'よろしくおねがいします',
        emoji: '🤝',
    },
];
