export type KanaItem = {
    character: string;
    romaji: string;
    example: string;
    exampleRomaji: string;
    exampleTranslation: string;
    emoji: string;
};

export const gojuonGrid = [
    ['あ', 'い', 'う', 'え', 'お'],
    ['か', 'き', 'く', 'け', 'こ'],
    ['さ', 'し', 'す', 'せ', 'そ'],
    ['た', 'ち', 'つ', 'て', 'と'],
    ['な', 'に', 'ぬ', 'ね', 'の'],
    ['は', 'ひ', 'ふ', 'へ', 'ほ'],
    ['ま', 'み', 'む', 'め', 'も'],
    ['や', null, 'ゆ', null, 'よ'],
    ['ら', 'り', 'る', 'れ', 'ろ'],
    ['わ', null, null, null, 'を'],
    ['ん', null, null, null, null],
];

export const dakutenHandakutenGrid = [
    ['が', 'ぎ', 'ぐ', 'げ', 'ご'],
    ['ざ', 'じ', 'ず', 'ぜ', 'ぞ'],
    ['だ', 'ぢ', 'づ', 'で', 'ど'],
    ['ば', 'び', 'ぶ', 'べ', 'ぼ'],
    ['ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ'],
];

export const yoonGrid = [
    ['きゃ', 'きゅ', 'きょ'],
    ['ぎゃ', 'ぎゅ', 'ぎょ'],
    ['しゃ', 'しゅ', 'しょ'],
    ['じゃ', 'じゅ', 'じょ'],
    ['ちゃ', 'ちゅ', 'ちょ'],
    ['ぢゃ', 'ぢゅ', 'ぢょ'],
    ['にゃ', 'にゅ', 'にょ'],
    ['ひゃ', 'ひゅ', 'ひょ'],
    ['びゃ', 'びゅ', 'びょ'],
    ['ぴゃ', 'ぴゅ', 'ぴょ'],
];

export const gojuon: KanaItem[] = [
    // A-row
    {
        character: 'あ',
        romaji: 'a',
        example: 'あめ',
        exampleRomaji: 'ame',
        exampleTranslation: 'rain',
        emoji: '🌧️',
    },
    {
        character: 'い',
        romaji: 'i',
        example: 'いぬ',
        exampleRomaji: 'inu',
        exampleTranslation: 'dog',
        emoji: '🐶',
    },
    {
        character: 'う',
        romaji: 'u',
        example: 'うみ',
        exampleRomaji: 'umi',
        exampleTranslation: 'sea',
        emoji: '🌊',
    },
    {
        character: 'え',
        romaji: 'e',
        example: 'えんぴつ',
        exampleRomaji: 'enpitsu',
        exampleTranslation: 'pencil',
        emoji: '✏️',
    },
    {
        character: 'お',
        romaji: 'o',
        example: 'おにぎり',
        exampleRomaji: 'onigiri',
        exampleTranslation: 'rice ball',
        emoji: '🍙',
    },

    // K-row
    {
        character: 'か',
        romaji: 'ka',
        example: 'かさ',
        exampleRomaji: 'kasa',
        exampleTranslation: 'umbrella',
        emoji: '☂️',
    },
    {
        character: 'き',
        romaji: 'ki',
        example: 'き',
        exampleRomaji: 'ki',
        exampleTranslation: 'tree',
        emoji: '🌳',
    },
    {
        character: 'く',
        romaji: 'ku',
        example: 'くるま',
        exampleRomaji: 'kuruma',
        exampleTranslation: 'car',
        emoji: '🚗',
    },
    {
        character: 'け',
        romaji: 'ke',
        example: 'けむし',
        exampleRomaji: 'kemushi',
        exampleTranslation: 'caterpillar',
        emoji: '🐛',
    },
    {
        character: 'こ',
        romaji: 'ko',
        example: 'こども',
        exampleRomaji: 'kodomo',
        exampleTranslation: 'child',
        emoji: '🧒',
    },

    // S-row
    {
        character: 'さ',
        romaji: 'sa',
        example: 'さくら',
        exampleRomaji: 'sakura',
        exampleTranslation: 'cherry blossom',
        emoji: '🌸',
    },
    {
        character: 'し',
        romaji: 'shi',
        example: 'しろ',
        exampleRomaji: 'shiro',
        exampleTranslation: 'castle',
        emoji: '🏯',
    },
    {
        character: 'す',
        romaji: 'su',
        example: 'すいか',
        exampleRomaji: 'suika',
        exampleTranslation: 'watermelon',
        emoji: '🍉',
    },
    {
        character: 'せ',
        romaji: 'se',
        example: 'せみ',
        exampleRomaji: 'semi',
        exampleTranslation: 'cicada',
        emoji: '🐞',
    },
    {
        character: 'そ',
        romaji: 'so',
        example: 'そら',
        exampleRomaji: 'sora',
        exampleTranslation: 'sky',
        emoji: '☁️',
    },

    // T-row
    {
        character: 'た',
        romaji: 'ta',
        example: 'たまご',
        exampleRomaji: 'tamago',
        exampleTranslation: 'egg',
        emoji: '🥚',
    },
    {
        character: 'ち',
        romaji: 'chi',
        example: 'ちず',
        exampleRomaji: 'chizu',
        exampleTranslation: 'map',
        emoji: '🗺️',
    },
    {
        character: 'つ',
        romaji: 'tsu',
        example: 'つき',
        exampleRomaji: 'tsuki',
        exampleTranslation: 'moon',
        emoji: '🌕',
    },
    {
        character: 'て',
        romaji: 'te',
        example: 'てがみ',
        exampleRomaji: 'tegami',
        exampleTranslation: 'letter',
        emoji: '📩',
    },
    {
        character: 'と',
        romaji: 'to',
        example: 'とけい',
        exampleRomaji: 'tokei',
        exampleTranslation: 'clock',
        emoji: '⏰',
    },

    // N-row
    {
        character: 'な',
        romaji: 'na',
        example: 'なつ',
        exampleRomaji: 'natsu',
        exampleTranslation: 'summer',
        emoji: '☀️',
    },
    {
        character: 'に',
        romaji: 'ni',
        example: 'にく',
        exampleRomaji: 'niku',
        exampleTranslation: 'meat',
        emoji: '🍖',
    },
    {
        character: 'ぬ',
        romaji: 'nu',
        example: 'ぬの',
        exampleRomaji: 'nuno',
        exampleTranslation: 'cloth',
        emoji: '🧵',
    },
    {
        character: 'ね',
        romaji: 'ne',
        example: 'ねこ',
        exampleRomaji: 'neko',
        exampleTranslation: 'cat',
        emoji: '🐱',
    },
    {
        character: 'の',
        romaji: 'no',
        example: 'のり',
        exampleRomaji: 'nori',
        exampleTranslation: 'seaweed',
        emoji: '🍘',
    },

    // H-row
    {
        character: 'は',
        romaji: 'ha',
        example: 'はな',
        exampleRomaji: 'hana',
        exampleTranslation: 'flower',
        emoji: '🌺',
    },
    {
        character: 'ひ',
        romaji: 'hi',
        example: 'ひこうき',
        exampleRomaji: 'hikouki',
        exampleTranslation: 'airplane',
        emoji: '✈️',
    },
    {
        character: 'ふ',
        romaji: 'fu',
        example: 'ふね',
        exampleRomaji: 'fune',
        exampleTranslation: 'boat',
        emoji: '🚢',
    },
    {
        character: 'へ',
        romaji: 'he',
        example: 'へび',
        exampleRomaji: 'hebi',
        exampleTranslation: 'snake',
        emoji: '🐍',
    },
    {
        character: 'ほ',
        romaji: 'ho',
        example: 'ほし',
        exampleRomaji: 'hoshi',
        exampleTranslation: 'star',
        emoji: '⭐',
    },

    // M-row
    {
        character: 'ま',
        romaji: 'ma',
        example: 'まど',
        exampleRomaji: 'mado',
        exampleTranslation: 'window',
        emoji: '🪟',
    },
    {
        character: 'み',
        romaji: 'mi',
        example: 'みみ',
        exampleRomaji: 'mimi',
        exampleTranslation: 'ear',
        emoji: '👂',
    },
    {
        character: 'む',
        romaji: 'mu',
        example: 'むし',
        exampleRomaji: 'mushi',
        exampleTranslation: 'insect',
        emoji: '🐜',
    },
    {
        character: 'め',
        romaji: 'me',
        example: 'め',
        exampleRomaji: 'me',
        exampleTranslation: 'eye',
        emoji: '👁️',
    },
    {
        character: 'も',
        romaji: 'mo',
        example: 'もも',
        exampleRomaji: 'momo',
        exampleTranslation: 'peach',
        emoji: '🍑',
    },

    // Y-row
    {
        character: 'や',
        romaji: 'ya',
        example: 'やま',
        exampleRomaji: 'yama',
        exampleTranslation: 'mountain',
        emoji: '⛰️',
    },
    {
        character: 'ゆ',
        romaji: 'yu',
        example: 'ゆき',
        exampleRomaji: 'yuki',
        exampleTranslation: 'snow',
        emoji: '❄️',
    },
    {
        character: 'よ',
        romaji: 'yo',
        example: 'よる',
        exampleRomaji: 'yoru',
        exampleTranslation: 'night',
        emoji: '🌃',
    },

    // R-row
    {
        character: 'ら',
        romaji: 'ra',
        example: 'らいおん',
        exampleRomaji: 'raion',
        exampleTranslation: 'lion',
        emoji: '🦁',
    },
    {
        character: 'り',
        romaji: 'ri',
        example: 'りんご',
        exampleRomaji: 'ringo',
        exampleTranslation: 'apple',
        emoji: '🍎',
    },
    {
        character: 'る',
        romaji: 'ru',
        example: 'るす',
        exampleRomaji: 'rusu',
        exampleTranslation: 'absence',
        emoji: '🚪',
    },
    {
        character: 'れ',
        romaji: 're',
        example: 'れいぞうこ',
        exampleRomaji: 'reizouko',
        exampleTranslation: 'refrigerator',
        emoji: '🧊',
    },
    {
        character: 'ろ',
        romaji: 'ro',
        example: 'ろうそく',
        exampleRomaji: 'rousoku',
        exampleTranslation: 'candle',
        emoji: '🕯️',
    },

    // W-row
    {
        character: 'わ',
        romaji: 'wa',
        example: 'わに',
        exampleRomaji: 'wani',
        exampleTranslation: 'crocodile',
        emoji: '🐊',
    },
    {
        character: 'を',
        romaji: 'wo',
        example: 'を',
        exampleRomaji: 'wo',
        exampleTranslation: 'object particle',
        emoji: '🔤',
    },

    // N
    {
        character: 'ん',
        romaji: 'n',
        example: 'ほん',
        exampleRomaji: 'hon',
        exampleTranslation: 'book',
        emoji: '📖',
    },
];

export const dakutenHandakuten: KanaItem[] = [
    // Dakuten - G-row
    {
        character: 'が',
        romaji: 'ga',
        example: 'がっこう',
        exampleRomaji: 'gakkou',
        exampleTranslation: 'school',
        emoji: '🏫',
    },
    {
        character: 'ぎ',
        romaji: 'gi',
        example: 'ぎんこう',
        exampleRomaji: 'ginkou',
        exampleTranslation: 'bank',
        emoji: '🏦',
    },
    {
        character: 'ぐ',
        romaji: 'gu',
        example: 'ぐんたい',
        exampleRomaji: 'guntai',
        exampleTranslation: 'army',
        emoji: '🎖️',
    },
    {
        character: 'げ',
        romaji: 'ge',
        example: 'げんき',
        exampleRomaji: 'genki',
        exampleTranslation: 'healthy',
        emoji: '💪',
    },
    {
        character: 'ご',
        romaji: 'go',
        example: 'ごはん',
        exampleRomaji: 'gohan',
        exampleTranslation: 'rice/meal',
        emoji: '🍚',
    },

    // Dakuten - Z-row
    {
        character: 'ざ',
        romaji: 'za',
        example: 'ざっし',
        exampleRomaji: 'zasshi',
        exampleTranslation: 'magazine',
        emoji: '📚',
    },
    {
        character: 'じ',
        romaji: 'ji',
        example: 'じてんしゃ',
        exampleRomaji: 'jitensha',
        exampleTranslation: 'bicycle',
        emoji: '🚲',
    },
    {
        character: 'ず',
        romaji: 'zu',
        example: 'ずこう',
        exampleRomaji: 'zukou',
        exampleTranslation: 'arts and crafts',
        emoji: '🎨',
    },
    {
        character: 'ぜ',
        romaji: 'ze',
        example: 'ぜんぶ',
        exampleRomaji: 'zenbu',
        exampleTranslation: 'everything',
        emoji: '🧺',
    },
    {
        character: 'ぞ',
        romaji: 'zo',
        example: 'ぞう',
        exampleRomaji: 'zou',
        exampleTranslation: 'elephant',
        emoji: '🐘',
    },

    // Dakuten - D-row
    {
        character: 'だ',
        romaji: 'da',
        example: 'だいがく',
        exampleRomaji: 'daigaku',
        exampleTranslation: 'university',
        emoji: '🎓',
    },
    {
        character: 'ぢ',
        romaji: 'ji',
        example: 'ちぢむ',
        exampleRomaji: 'chijimu',
        exampleTranslation: 'shrink',
        emoji: '📏',
    },
    {
        character: 'づ',
        romaji: 'zu',
        example: 'つづく',
        exampleRomaji: 'tsuzuku',
        exampleTranslation: 'to continue',
        emoji: '🔁',
    },
    {
        character: 'で',
        romaji: 'de',
        example: 'でんしゃ',
        exampleRomaji: 'densha',
        exampleTranslation: 'train',
        emoji: '🚆',
    },
    {
        character: 'ど',
        romaji: 'do',
        example: 'どようび',
        exampleRomaji: 'doyoubi',
        exampleTranslation: 'Saturday',
        emoji: '📅',
    },

    // Dakuten - B-row
    {
        character: 'ば',
        romaji: 'ba',
        example: 'ばしょ',
        exampleRomaji: 'basho',
        exampleTranslation: 'place',
        emoji: '📍',
    },
    {
        character: 'び',
        romaji: 'bi',
        example: 'びょういん',
        exampleRomaji: 'byouin',
        exampleTranslation: 'hospital',
        emoji: '🏥',
    },
    {
        character: 'ぶ',
        romaji: 'bu',
        example: 'ぶた',
        exampleRomaji: 'buta',
        exampleTranslation: 'pig',
        emoji: '🐷',
    },
    {
        character: 'べ',
        romaji: 'be',
        example: 'べんきょう',
        exampleRomaji: 'benkyou',
        exampleTranslation: 'study',
        emoji: '📖',
    },
    {
        character: 'ぼ',
        romaji: 'bo',
        example: 'ぼうし',
        exampleRomaji: 'boushi',
        exampleTranslation: 'hat',
        emoji: '👒',
    },

    // Handakuten - P-row
    {
        character: 'ぱ',
        romaji: 'pa',
        example: 'ぱん',
        exampleRomaji: 'pan',
        exampleTranslation: 'bread',
        emoji: '🍞',
    },
    {
        character: 'ぴ',
        romaji: 'pi',
        example: 'ぴあの',
        exampleRomaji: 'piano',
        exampleTranslation: 'piano',
        emoji: '🎹',
    },
    {
        character: 'ぷ',
        romaji: 'pu',
        example: 'ぷーる',
        exampleRomaji: 'puuru',
        exampleTranslation: 'pool',
        emoji: '🏊',
    },
    {
        character: 'ぺ',
        romaji: 'pe',
        example: 'ぺん',
        exampleRomaji: 'pen',
        exampleTranslation: 'pen',
        emoji: '🖊️',
    },
    {
        character: 'ぽ',
        romaji: 'po',
        example: 'ぽすと',
        exampleRomaji: 'posuto',
        exampleTranslation: 'mailbox',
        emoji: '📮',
    },
];

export const yoon: KanaItem[] = [
    // K-yoon
    {
        character: 'きゃ',
        romaji: 'kya',
        example: 'きゃく',
        exampleRomaji: 'kyaku',
        exampleTranslation: 'guest',
        emoji: '🧳',
    },
    {
        character: 'きゅ',
        romaji: 'kyu',
        example: 'きゅうり',
        exampleRomaji: 'kyuuri',
        exampleTranslation: 'cucumber',
        emoji: '🥒',
    },
    {
        character: 'きょ',
        romaji: 'kyo',
        example: 'きょう',
        exampleRomaji: 'kyou',
        exampleTranslation: 'today',
        emoji: '📆',
    },

    // G-yoon
    {
        character: 'ぎゃ',
        romaji: 'gya',
        example: 'ぎゃく',
        exampleRomaji: 'gyaku',
        exampleTranslation: 'reverse/opposite',
        emoji: '🔁',
    },
    {
        character: 'ぎゅ',
        romaji: 'gyu',
        example: 'ぎゅうにゅう',
        exampleRomaji: 'gyuunyuu',
        exampleTranslation: 'milk',
        emoji: '🥛',
    },
    {
        character: 'ぎょ',
        romaji: 'gyo',
        example: 'ぎょかいるい',
        exampleRomaji: 'gyokairui',
        exampleTranslation: 'seafood',
        emoji: '🦐',
    },

    // S-yoon
    {
        character: 'しゃ',
        romaji: 'sha',
        example: 'しゃしん',
        exampleRomaji: 'shashin',
        exampleTranslation: 'photo',
        emoji: '📸',
    },
    {
        character: 'しゅ',
        romaji: 'shu',
        example: 'しゅくだい',
        exampleRomaji: 'shukudai',
        exampleTranslation: 'homework',
        emoji: '📚',
    },
    {
        character: 'しょ',
        romaji: 'sho',
        example: 'しょうゆ',
        exampleRomaji: 'shouyu',
        exampleTranslation: 'soy sauce',
        emoji: '🧂',
    },

    // J-yoon (from じ)
    {
        character: 'じゃ',
        romaji: 'ja',
        example: 'じゃがいも',
        exampleRomaji: 'jagaimo',
        exampleTranslation: 'potato',
        emoji: '🥔',
    },
    {
        character: 'じゅ',
        romaji: 'ju',
        example: 'じゅぎょう',
        exampleRomaji: 'jugyou',
        exampleTranslation: 'class/lesson',
        emoji: '🏫',
    },
    {
        character: 'じょ',
        romaji: 'jo',
        example: 'じょせい',
        exampleRomaji: 'josei',
        exampleTranslation: 'woman',
        emoji: '👩',
    },

    // T-yoon (actually CH-yoon)
    {
        character: 'ちゃ',
        romaji: 'cha',
        example: 'ちゃわん',
        exampleRomaji: 'chawan',
        exampleTranslation: 'rice bowl',
        emoji: '🍚',
    },
    {
        character: 'ちゅ',
        romaji: 'chu',
        example: 'ちゅうごく',
        exampleRomaji: 'chuugoku',
        exampleTranslation: 'China',
        emoji: '🇨🇳',
    },
    {
        character: 'ちょ',
        romaji: 'cho',
        example: 'ちょこれーと',
        exampleRomaji: 'chokoreeto',
        exampleTranslation: 'chocolate',
        emoji: '🍫',
    },

    // D-yoon (from ぢ/づ, but use じ/ず spelling conventionally)
    {
        character: 'ぢゃ',
        romaji: 'ja',
        example: 'ぢゃみせ',
        exampleRomaji: 'jamise',
        exampleTranslation: 'teahouse',
        emoji: '🍵',
    }, // rare
    {
        character: 'ぢゅ',
        romaji: 'ju',
        example: 'ぢゅん',
        exampleRomaji: 'jun',
        exampleTranslation: 'name (Jun)',
        emoji: '🧑‍🎓',
    }, // used in names
    {
        character: 'ぢょ',
        romaji: 'jo',
        example: 'ぢょくせん',
        exampleRomaji: 'jokusen',
        exampleTranslation: 'direct line',
        emoji: '📞',
    }, // uncommon

    // N-yoon
    {
        character: 'にゃ',
        romaji: 'nya',
        example: 'にゃんこ',
        exampleRomaji: 'nyanko',
        exampleTranslation: 'kitty',
        emoji: '🐱',
    },
    {
        character: 'にゅ',
        romaji: 'nyu',
        example: 'にゅういん',
        exampleRomaji: 'nyuuin',
        exampleTranslation: 'hospitalization',
        emoji: '🏥',
    },
    {
        character: 'にょ',
        romaji: 'nyo',
        example: 'にょろにょろ',
        exampleRomaji: 'nyoronyoro',
        exampleTranslation: 'wiggling',
        emoji: '🪱',
    },

    // H-yoon
    {
        character: 'ひゃ',
        romaji: 'hya',
        example: 'ひゃく',
        exampleRomaji: 'hyaku',
        exampleTranslation: 'hundred',
        emoji: '💯',
    },
    {
        character: 'ひゅ',
        romaji: 'hyu',
        example: 'ひゅうひゅう',
        exampleRomaji: 'hyuuhyuu',
        exampleTranslation: 'whistling (wind)',
        emoji: '🌬️',
    },
    {
        character: 'ひょ',
        romaji: 'hyo',
        example: 'ひょう',
        exampleRomaji: 'hyou',
        exampleTranslation: 'leopard / chart',
        emoji: '🐆',
    },

    // B-yoon
    {
        character: 'びゃ',
        romaji: 'bya',
        example: 'びゃくや',
        exampleRomaji: 'byakuya',
        exampleTranslation: 'white night',
        emoji: '🌃',
    },
    {
        character: 'びゅ',
        romaji: 'byu',
        example: 'びゅうびゅう',
        exampleRomaji: 'byuubuu',
        exampleTranslation: 'wind blowing hard',
        emoji: '🌪️',
    },
    {
        character: 'びょ',
        romaji: 'byo',
        example: 'びょういん',
        exampleRomaji: 'byouin',
        exampleTranslation: 'hospital',
        emoji: '🏥',
    },

    // P-yoon
    {
        character: 'ぴゃ',
        romaji: 'pya',
        example: 'ぴゃっこい',
        exampleRomaji: 'pyakkoi',
        exampleTranslation: 'chilly (Tohoku dialect)',
        emoji: '❄️',
    },
    {
        character: 'ぴゅ',
        romaji: 'pyu',
        example: 'ぴゅうぴゅう',
        exampleRomaji: 'pyuupuu',
        exampleTranslation: 'wind blowing sound',
        emoji: '💨',
    },
    {
        character: 'ぴょ',
        romaji: 'pyo',
        example: 'ぴょんぴょん',
        exampleRomaji: 'pyonpyon',
        exampleTranslation: 'hopping',
        emoji: '🐇',
    },
];

export const hiraganaItems: KanaItem[] = [...gojuon, ...dakutenHandakuten, ...yoon];
