export type KanaItem = {
    character: string;
    romanji: string;
    example: string;
    exampleRomanji: string;
    exampleTranslation: string;
    emoji: string;
};

export const gojuonGrid = [
    ['あ', 'い', 'う', 'え', 'お'],
    ['か', 'き', 'く', 'け', 'こ'],
    ['さ', 'し', 'す', 'せ', 'そ'],
    ['た', 'ち', 'つ', 'て', 'と'],
    ['な', 'に', 'ぬ', 'ね', 'の'],
    ['は', 'ひ', 'ふ', 'へ', 'ほ'],
    ['ま', 'み', 'む', 'め', 'も'],
    ['や', null, 'ゆ', null, 'よ'],
    ['ら', 'り', 'る', 'れ', 'ろ'],
    ['わ', null, null, null, 'を'],
    ['ん', null, null, null, null],
];

export const dakutenHandakutenGrid = [
    ['が', 'ぎ', 'ぐ', 'げ', 'ご'],
    ['ざ', 'じ', 'ず', 'ぜ', 'ぞ'],
    ['だ', 'ぢ', 'づ', 'で', 'ど'],
    ['ば', 'び', 'ぶ', 'べ', 'ぼ'],
    ['ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ'],
];

export const yoonGrid = [
    ['きゃ', 'きゅ', 'きょ'],
    ['ぎゃ', 'ぎゅ', 'ぎょ'],
    ['しゃ', 'しゅ', 'しょ'],
    ['じゃ', 'じゅ', 'じょ'],
    ['ちゃ', 'ちゅ', 'ちょ'],
    ['ぢゃ', 'ぢゅ', 'ぢょ'],
    ['にゃ', 'にゅ', 'にょ'],
    ['ひゃ', 'ひゅ', 'ひょ'],
    ['びゃ', 'びゅ', 'びょ'],
    ['ぴゃ', 'ぴゅ', 'ぴょ'],
];

export const gojuon: KanaItem[] = [
    // A-row
    {
        character: 'あ',
        romanji: 'a',
        example: 'あめ',
        exampleRomanji: 'ame',
        exampleTranslation: 'rain',
        emoji: '🌧️',
    },
    {
        character: 'い',
        romanji: 'i',
        example: 'いぬ',
        exampleRomanji: 'inu',
        exampleTranslation: 'dog',
        emoji: '🐶',
    },
    {
        character: 'う',
        romanji: 'u',
        example: 'うみ',
        exampleRomanji: 'umi',
        exampleTranslation: 'sea',
        emoji: '🌊',
    },
    {
        character: 'え',
        romanji: 'e',
        example: 'えんぴつ',
        exampleRomanji: 'enpitsu',
        exampleTranslation: 'pencil',
        emoji: '✏️',
    },
    {
        character: 'お',
        romanji: 'o',
        example: 'おにぎり',
        exampleRomanji: 'onigiri',
        exampleTranslation: 'rice ball',
        emoji: '🍙',
    },

    // K-row
    {
        character: 'か',
        romanji: 'ka',
        example: 'かさ',
        exampleRomanji: 'kasa',
        exampleTranslation: 'umbrella',
        emoji: '☂️',
    },
    {
        character: 'き',
        romanji: 'ki',
        example: 'き',
        exampleRomanji: 'ki',
        exampleTranslation: 'tree',
        emoji: '🌳',
    },
    {
        character: 'く',
        romanji: 'ku',
        example: 'くるま',
        exampleRomanji: 'kuruma',
        exampleTranslation: 'car',
        emoji: '🚗',
    },
    {
        character: 'け',
        romanji: 'ke',
        example: 'けむし',
        exampleRomanji: 'kemushi',
        exampleTranslation: 'caterpillar',
        emoji: '🐛',
    },
    {
        character: 'こ',
        romanji: 'ko',
        example: 'こども',
        exampleRomanji: 'kodomo',
        exampleTranslation: 'child',
        emoji: '🧒',
    },

    // S-row
    {
        character: 'さ',
        romanji: 'sa',
        example: 'さくら',
        exampleRomanji: 'sakura',
        exampleTranslation: 'cherry blossom',
        emoji: '🌸',
    },
    {
        character: 'し',
        romanji: 'shi',
        example: 'しろ',
        exampleRomanji: 'shiro',
        exampleTranslation: 'castle',
        emoji: '🏯',
    },
    {
        character: 'す',
        romanji: 'su',
        example: 'すいか',
        exampleRomanji: 'suika',
        exampleTranslation: 'watermelon',
        emoji: '🍉',
    },
    {
        character: 'せ',
        romanji: 'se',
        example: 'せみ',
        exampleRomanji: 'semi',
        exampleTranslation: 'cicada',
        emoji: '🐞',
    },
    {
        character: 'そ',
        romanji: 'so',
        example: 'そら',
        exampleRomanji: 'sora',
        exampleTranslation: 'sky',
        emoji: '☁️',
    },

    // T-row
    {
        character: 'た',
        romanji: 'ta',
        example: 'たまご',
        exampleRomanji: 'tamago',
        exampleTranslation: 'egg',
        emoji: '🥚',
    },
    {
        character: 'ち',
        romanji: 'chi',
        example: 'ちず',
        exampleRomanji: 'chizu',
        exampleTranslation: 'map',
        emoji: '🗺️',
    },
    {
        character: 'つ',
        romanji: 'tsu',
        example: 'つき',
        exampleRomanji: 'tsuki',
        exampleTranslation: 'moon',
        emoji: '🌕',
    },
    {
        character: 'て',
        romanji: 'te',
        example: 'てがみ',
        exampleRomanji: 'tegami',
        exampleTranslation: 'letter',
        emoji: '📩',
    },
    {
        character: 'と',
        romanji: 'to',
        example: 'とけい',
        exampleRomanji: 'tokei',
        exampleTranslation: 'clock',
        emoji: '⏰',
    },

    // N-row
    {
        character: 'な',
        romanji: 'na',
        example: 'なつ',
        exampleRomanji: 'natsu',
        exampleTranslation: 'summer',
        emoji: '☀️',
    },
    {
        character: 'に',
        romanji: 'ni',
        example: 'にく',
        exampleRomanji: 'niku',
        exampleTranslation: 'meat',
        emoji: '🍖',
    },
    {
        character: 'ぬ',
        romanji: 'nu',
        example: 'ぬの',
        exampleRomanji: 'nuno',
        exampleTranslation: 'cloth',
        emoji: '🧵',
    },
    {
        character: 'ね',
        romanji: 'ne',
        example: 'ねこ',
        exampleRomanji: 'neko',
        exampleTranslation: 'cat',
        emoji: '🐱',
    },
    {
        character: 'の',
        romanji: 'no',
        example: 'のり',
        exampleRomanji: 'nori',
        exampleTranslation: 'seaweed',
        emoji: '🍘',
    },

    // H-row
    {
        character: 'は',
        romanji: 'ha',
        example: 'はな',
        exampleRomanji: 'hana',
        exampleTranslation: 'flower',
        emoji: '🌺',
    },
    {
        character: 'ひ',
        romanji: 'hi',
        example: 'ひこうき',
        exampleRomanji: 'hikouki',
        exampleTranslation: 'airplane',
        emoji: '✈️',
    },
    {
        character: 'ふ',
        romanji: 'fu',
        example: 'ふね',
        exampleRomanji: 'fune',
        exampleTranslation: 'boat',
        emoji: '🚢',
    },
    {
        character: 'へ',
        romanji: 'he',
        example: 'へび',
        exampleRomanji: 'hebi',
        exampleTranslation: 'snake',
        emoji: '🐍',
    },
    {
        character: 'ほ',
        romanji: 'ho',
        example: 'ほし',
        exampleRomanji: 'hoshi',
        exampleTranslation: 'star',
        emoji: '⭐',
    },

    // M-row
    {
        character: 'ま',
        romanji: 'ma',
        example: 'まど',
        exampleRomanji: 'mado',
        exampleTranslation: 'window',
        emoji: '🪟',
    },
    {
        character: 'み',
        romanji: 'mi',
        example: 'みみ',
        exampleRomanji: 'mimi',
        exampleTranslation: 'ear',
        emoji: '👂',
    },
    {
        character: 'む',
        romanji: 'mu',
        example: 'むし',
        exampleRomanji: 'mushi',
        exampleTranslation: 'insect',
        emoji: '🐜',
    },
    {
        character: 'め',
        romanji: 'me',
        example: 'め',
        exampleRomanji: 'me',
        exampleTranslation: 'eye',
        emoji: '👁️',
    },
    {
        character: 'も',
        romanji: 'mo',
        example: 'もも',
        exampleRomanji: 'momo',
        exampleTranslation: 'peach',
        emoji: '🍑',
    },

    // Y-row
    {
        character: 'や',
        romanji: 'ya',
        example: 'やま',
        exampleRomanji: 'yama',
        exampleTranslation: 'mountain',
        emoji: '⛰️',
    },
    {
        character: 'ゆ',
        romanji: 'yu',
        example: 'ゆき',
        exampleRomanji: 'yuki',
        exampleTranslation: 'snow',
        emoji: '❄️',
    },
    {
        character: 'よ',
        romanji: 'yo',
        example: 'よる',
        exampleRomanji: 'yoru',
        exampleTranslation: 'night',
        emoji: '🌃',
    },

    // R-row
    {
        character: 'ら',
        romanji: 'ra',
        example: 'らいおん',
        exampleRomanji: 'raion',
        exampleTranslation: 'lion',
        emoji: '🦁',
    },
    {
        character: 'り',
        romanji: 'ri',
        example: 'りんご',
        exampleRomanji: 'ringo',
        exampleTranslation: 'apple',
        emoji: '🍎',
    },
    {
        character: 'る',
        romanji: 'ru',
        example: 'るす',
        exampleRomanji: 'rusu',
        exampleTranslation: 'absence',
        emoji: '🚪',
    },
    {
        character: 'れ',
        romanji: 're',
        example: 'れいぞうこ',
        exampleRomanji: 'reizouko',
        exampleTranslation: 'refrigerator',
        emoji: '🧊',
    },
    {
        character: 'ろ',
        romanji: 'ro',
        example: 'ろうそく',
        exampleRomanji: 'rousoku',
        exampleTranslation: 'candle',
        emoji: '🕯️',
    },

    // W-row
    {
        character: 'わ',
        romanji: 'wa',
        example: 'わに',
        exampleRomanji: 'wani',
        exampleTranslation: 'crocodile',
        emoji: '🐊',
    },
    {
        character: 'を',
        romanji: 'wo',
        example: 'を',
        exampleRomanji: 'wo',
        exampleTranslation: 'object particle',
        emoji: '🔤',
    },

    // N
    {
        character: 'ん',
        romanji: 'n',
        example: 'ほん',
        exampleRomanji: 'hon',
        exampleTranslation: 'book',
        emoji: '📖',
    },
];

export const dakutenHandakuten: KanaItem[] = [
    // Dakuten - G-row
    {
        character: 'が',
        romanji: 'ga',
        example: 'がっこう',
        exampleRomanji: 'gakkou',
        exampleTranslation: 'school',
        emoji: '🏫',
    },
    {
        character: 'ぎ',
        romanji: 'gi',
        example: 'ぎんこう',
        exampleRomanji: 'ginkou',
        exampleTranslation: 'bank',
        emoji: '🏦',
    },
    {
        character: 'ぐ',
        romanji: 'gu',
        example: 'ぐんたい',
        exampleRomanji: 'guntai',
        exampleTranslation: 'army',
        emoji: '🎖️',
    },
    {
        character: 'げ',
        romanji: 'ge',
        example: 'げんき',
        exampleRomanji: 'genki',
        exampleTranslation: 'healthy',
        emoji: '💪',
    },
    {
        character: 'ご',
        romanji: 'go',
        example: 'ごはん',
        exampleRomanji: 'gohan',
        exampleTranslation: 'rice/meal',
        emoji: '🍚',
    },

    // Dakuten - Z-row
    {
        character: 'ざ',
        romanji: 'za',
        example: 'ざっし',
        exampleRomanji: 'zasshi',
        exampleTranslation: 'magazine',
        emoji: '📚',
    },
    {
        character: 'じ',
        romanji: 'ji',
        example: 'じてんしゃ',
        exampleRomanji: 'jitensha',
        exampleTranslation: 'bicycle',
        emoji: '🚲',
    },
    {
        character: 'ず',
        romanji: 'zu',
        example: 'ずこう',
        exampleRomanji: 'zukou',
        exampleTranslation: 'arts and crafts',
        emoji: '🎨',
    },
    {
        character: 'ぜ',
        romanji: 'ze',
        example: 'ぜんぶ',
        exampleRomanji: 'zenbu',
        exampleTranslation: 'everything',
        emoji: '🧺',
    },
    {
        character: 'ぞ',
        romanji: 'zo',
        example: 'ぞう',
        exampleRomanji: 'zou',
        exampleTranslation: 'elephant',
        emoji: '🐘',
    },

    // Dakuten - D-row
    {
        character: 'だ',
        romanji: 'da',
        example: 'だいがく',
        exampleRomanji: 'daigaku',
        exampleTranslation: 'university',
        emoji: '🎓',
    },
    {
        character: 'ぢ',
        romanji: 'ji',
        example: 'ちぢむ',
        exampleRomanji: 'chijimu',
        exampleTranslation: 'shrink',
        emoji: '📏',
    },
    {
        character: 'づ',
        romanji: 'zu',
        example: 'つづく',
        exampleRomanji: 'tsuzuku',
        exampleTranslation: 'to continue',
        emoji: '🔁',
    },
    {
        character: 'で',
        romanji: 'de',
        example: 'でんしゃ',
        exampleRomanji: 'densha',
        exampleTranslation: 'train',
        emoji: '🚆',
    },
    {
        character: 'ど',
        romanji: 'do',
        example: 'どようび',
        exampleRomanji: 'doyoubi',
        exampleTranslation: 'Saturday',
        emoji: '📅',
    },

    // Dakuten - B-row
    {
        character: 'ば',
        romanji: 'ba',
        example: 'ばしょ',
        exampleRomanji: 'basho',
        exampleTranslation: 'place',
        emoji: '📍',
    },
    {
        character: 'び',
        romanji: 'bi',
        example: 'びょういん',
        exampleRomanji: 'byouin',
        exampleTranslation: 'hospital',
        emoji: '🏥',
    },
    {
        character: 'ぶ',
        romanji: 'bu',
        example: 'ぶた',
        exampleRomanji: 'buta',
        exampleTranslation: 'pig',
        emoji: '🐷',
    },
    {
        character: 'べ',
        romanji: 'be',
        example: 'べんきょう',
        exampleRomanji: 'benkyou',
        exampleTranslation: 'study',
        emoji: '📖',
    },
    {
        character: 'ぼ',
        romanji: 'bo',
        example: 'ぼうし',
        exampleRomanji: 'boushi',
        exampleTranslation: 'hat',
        emoji: '👒',
    },

    // Handakuten - P-row
    {
        character: 'ぱ',
        romanji: 'pa',
        example: 'ぱちぱち',
        exampleRomanji: 'pachipachi',
        exampleTranslation: 'crackling/clapping sound',
        emoji: '👏',
    },
    {
        character: 'ぴ',
        romanji: 'pi',
        example: 'ぴかぴか',
        exampleRomanji: 'pikapika',
        exampleTranslation: 'sparkling/shiny',
        emoji: '✨',
    },
    {
        character: 'ぷ',
        romanji: 'pu',
        example: 'ぷかぷか',
        exampleRomanji: 'pukapuka',
        exampleTranslation: 'floating/bobbing',
        emoji: '🌊',
    },
    {
        character: 'ぺ',
        romanji: 'pe',
        example: 'ぺこぺこ',
        exampleRomanji: 'pekopeko',
        exampleTranslation: 'very hungry/bowing repeatedly',
        emoji: '🙇',
    },
    {
        character: 'ぽ',
        romanji: 'po',
        example: 'ぽかぽか',
        exampleRomanji: 'pokapoka',
        exampleTranslation: 'warm and cozy',
        emoji: '☀️',
    },
];

export const yoon: KanaItem[] = [
    // K-yoon
    {
        character: 'きゃ',
        romanji: 'kya',
        example: 'きゃく',
        exampleRomanji: 'kyaku',
        exampleTranslation: 'guest',
        emoji: '🧳',
    },
    {
        character: 'きゅ',
        romanji: 'kyu',
        example: 'きゅうり',
        exampleRomanji: 'kyuuri',
        exampleTranslation: 'cucumber',
        emoji: '🥒',
    },
    {
        character: 'きょ',
        romanji: 'kyo',
        example: 'きょう',
        exampleRomanji: 'kyou',
        exampleTranslation: 'today',
        emoji: '📆',
    },

    // G-yoon
    {
        character: 'ぎゃ',
        romanji: 'gya',
        example: 'ぎゃく',
        exampleRomanji: 'gyaku',
        exampleTranslation: 'reverse/opposite',
        emoji: '🔁',
    },
    {
        character: 'ぎゅ',
        romanji: 'gyu',
        example: 'ぎゅうにゅう',
        exampleRomanji: 'gyuunyuu',
        exampleTranslation: 'milk',
        emoji: '🥛',
    },
    {
        character: 'ぎょ',
        romanji: 'gyo',
        example: 'ぎょかいるい',
        exampleRomanji: 'gyokairui',
        exampleTranslation: 'seafood',
        emoji: '🦐',
    },

    // S-yoon
    {
        character: 'しゃ',
        romanji: 'sha',
        example: 'しゃしん',
        exampleRomanji: 'shashin',
        exampleTranslation: 'photo',
        emoji: '📸',
    },
    {
        character: 'しゅ',
        romanji: 'shu',
        example: 'しゅくだい',
        exampleRomanji: 'shukudai',
        exampleTranslation: 'homework',
        emoji: '📚',
    },
    {
        character: 'しょ',
        romanji: 'sho',
        example: 'しょうゆ',
        exampleRomanji: 'shouyu',
        exampleTranslation: 'soy sauce',
        emoji: '🧂',
    },

    // J-yoon (from じ)
    {
        character: 'じゃ',
        romanji: 'ja',
        example: 'じゃがいも',
        exampleRomanji: 'jagaimo',
        exampleTranslation: 'potato',
        emoji: '🥔',
    },
    {
        character: 'じゅ',
        romanji: 'ju',
        example: 'じゅぎょう',
        exampleRomanji: 'jugyou',
        exampleTranslation: 'class/lesson',
        emoji: '🏫',
    },
    {
        character: 'じょ',
        romanji: 'jo',
        example: 'じょせい',
        exampleRomanji: 'josei',
        exampleTranslation: 'woman',
        emoji: '👩',
    },

    // T-yoon (actually CH-yoon)
    {
        character: 'ちゃ',
        romanji: 'cha',
        example: 'ちゃわん',
        exampleRomanji: 'chawan',
        exampleTranslation: 'rice bowl',
        emoji: '🍚',
    },
    {
        character: 'ちゅ',
        romanji: 'chu',
        example: 'ちゅうごく',
        exampleRomanji: 'chuugoku',
        exampleTranslation: 'China',
        emoji: '🇨🇳',
    },
    {
        character: 'ちょ',
        romanji: 'cho',
        example: 'ちょっと',
        exampleRomanji: 'chotto',
        exampleTranslation: 'a little/just a moment',
        emoji: '🤏',
    },

    // D-yoon (from ぢ/づ, but use じ/ず spelling conventionally)
    {
        character: 'ぢゃ',
        romanji: 'ja',
        example: 'そうぢゃ',
        exampleRomanji: 'souja',
        exampleTranslation: "that's right (Kyushu dialect)",
        emoji: '🗾',
    }, // rare — dialectal
    {
        character: 'ぢゅ',
        romanji: 'ju',
        example: 'まんぢゅう',
        exampleRomanji: 'manjuu',
        exampleTranslation: 'steamed bun (historical kana)',
        emoji: '🥮',
    }, // rare — historical kana spelling of まんじゅう
    {
        character: 'ぢょ',
        romanji: 'jo',
        example: 'ぢょっぴり',
        exampleRomanji: 'joppiri',
        exampleTranslation: 'just a tiny bit (informal variant of ちょっぴり)',
        emoji: '🤏',
    }, // rare — informal/dialectal

    // N-yoon
    {
        character: 'にゃ',
        romanji: 'nya',
        example: 'にゃんこ',
        exampleRomanji: 'nyanko',
        exampleTranslation: 'kitty',
        emoji: '🐱',
    },
    {
        character: 'にゅ',
        romanji: 'nyu',
        example: 'にゅういん',
        exampleRomanji: 'nyuuin',
        exampleTranslation: 'hospitalization',
        emoji: '🏥',
    },
    {
        character: 'にょ',
        romanji: 'nyo',
        example: 'にょろにょろ',
        exampleRomanji: 'nyoronyoro',
        exampleTranslation: 'wiggling',
        emoji: '🪱',
    },

    // H-yoon
    {
        character: 'ひゃ',
        romanji: 'hya',
        example: 'ひゃく',
        exampleRomanji: 'hyaku',
        exampleTranslation: 'hundred',
        emoji: '💯',
    },
    {
        character: 'ひゅ',
        romanji: 'hyu',
        example: 'ひゅうひゅう',
        exampleRomanji: 'hyuuhyuu',
        exampleTranslation: 'whistling (wind)',
        emoji: '🌬️',
    },
    {
        character: 'ひょ',
        romanji: 'hyo',
        example: 'ひょう',
        exampleRomanji: 'hyou',
        exampleTranslation: 'leopard / chart',
        emoji: '🐆',
    },

    // B-yoon
    {
        character: 'びゃ',
        romanji: 'bya',
        example: 'びゃくや',
        exampleRomanji: 'byakuya',
        exampleTranslation: 'white night',
        emoji: '🌃',
    },
    {
        character: 'びゅ',
        romanji: 'byu',
        example: 'びゅうびゅう',
        exampleRomanji: 'byuubuu',
        exampleTranslation: 'wind blowing hard',
        emoji: '🌪️',
    },
    {
        character: 'びょ',
        romanji: 'byo',
        example: 'びょういん',
        exampleRomanji: 'byouin',
        exampleTranslation: 'hospital',
        emoji: '🏥',
    },

    // P-yoon
    {
        character: 'ぴゃ',
        romanji: 'pya',
        example: 'ぴゃっこい',
        exampleRomanji: 'pyakkoi',
        exampleTranslation: 'chilly (Tohoku dialect)',
        emoji: '❄️',
    },
    {
        character: 'ぴゅ',
        romanji: 'pyu',
        example: 'ぴゅうぴゅう',
        exampleRomanji: 'pyuupuu',
        exampleTranslation: 'wind blowing sound',
        emoji: '💨',
    },
    {
        character: 'ぴょ',
        romanji: 'pyo',
        example: 'ぴょんぴょん',
        exampleRomanji: 'pyonpyon',
        exampleTranslation: 'hopping',
        emoji: '🐇',
    },
];

export const hiraganaItems: KanaItem[] = [...gojuon, ...dakutenHandakuten, ...yoon];
