import { KanaItem } from './hiragana';

export const gojuonGrid = [
    ['ア', 'イ', 'ウ', 'エ', 'オ'],
    ['カ', 'キ', 'ク', 'ケ', 'コ'],
    ['サ', 'シ', 'ス', 'セ', 'ソ'],
    ['タ', 'チ', 'ツ', 'テ', 'ト'],
    ['ナ', 'ニ', 'ヌ', 'ネ', 'ノ'],
    ['ハ', 'ヒ', 'フ', 'ヘ', 'ホ'],
    ['マ', 'ミ', 'ム', 'メ', 'モ'],
    ['ヤ', null, 'ユ', null, 'ヨ'],
    ['ラ', 'リ', 'ル', 'レ', 'ロ'],
    ['ワ', null, null, null, 'ヲ'],
    ['ン', null, null, null, null],
];

export const dakutenHandakutenGrid = [
    ['ガ', 'ギ', 'グ', 'ゲ', 'ゴ'],
    ['ザ', 'ジ', 'ズ', 'ゼ', 'ゾ'],
    ['ダ', 'ヂ', 'ヅ', 'デ', 'ド'],
    ['バ', 'ビ', 'ブ', 'ベ', 'ボ'],
    ['パ', 'ピ', 'プ', 'ペ', 'ポ'],
];

export const yoonGrid = [
    ['キャ', 'キュ', 'キョ'],
    ['ギャ', 'ギュ', 'ギョ'],
    ['シャ', 'シュ', 'ショ'],
    ['ジャ', 'ジュ', 'ジョ'],
    ['チャ', 'チュ', 'チョ'],
    ['ヂャ', 'ヂュ', 'ヂョ'],
    ['ニャ', 'ニュ', 'ニョ'],
    ['ヒャ', 'ヒュ', 'ヒョ'],
    ['ビャ', 'ビュ', 'ビョ'],
    ['ピャ', 'ピュ', 'ピョ'],
];

export const gojuon: KanaItem[] = [
    // A-row
    {
        character: 'ア',
        romanji: 'A',
        example: 'アイスクリーム',
        exampleRomanji: 'aisukuriimu',
        exampleTranslation: 'ice cream',
        emoji: '🍦',
    },
    {
        character: 'イ',
        romanji: 'I',
        example: 'インク',
        exampleRomanji: 'inku',
        exampleTranslation: 'ink',
        emoji: '✒️',
    },
    {
        character: 'ウ',
        romanji: 'U',
        example: 'ウイルス',
        exampleRomanji: 'uirusu',
        exampleTranslation: 'virus',
        emoji: '🦠',
    },
    {
        character: 'エ',
        romanji: 'E',
        example: 'エレベーター',
        exampleRomanji: 'erebeetaa',
        exampleTranslation: 'elevator',
        emoji: '🛗',
    },
    {
        character: 'オ',
        romanji: 'O',
        example: 'オレンジ',
        exampleRomanji: 'orenji',
        exampleTranslation: 'orange',
        emoji: '🍊',
    },
    // K-row
    {
        character: 'カ',
        romanji: 'KA',
        example: 'カメラ',
        exampleRomanji: 'kamera',
        exampleTranslation: 'camera',
        emoji: '📷',
    },
    {
        character: 'キ',
        romanji: 'KI',
        example: 'キー',
        exampleRomanji: 'kii',
        exampleTranslation: 'key',
        emoji: '🔑',
    },
    {
        character: 'ク',
        romanji: 'KU',
        example: 'クラス',
        exampleRomanji: 'kurasu',
        exampleTranslation: 'class',
        emoji: '🧑‍🏫',
    },
    {
        character: 'ケ',
        romanji: 'KE',
        example: 'ケーキ',
        exampleRomanji: 'keeki',
        exampleTranslation: 'cake',
        emoji: '🍰',
    },
    {
        character: 'コ',
        romanji: 'KO',
        example: 'コーヒー',
        exampleRomanji: 'koohii',
        exampleTranslation: 'coffee',
        emoji: '☕',
    },
    // S-row
    {
        character: 'サ',
        romanji: 'SA',
        example: 'サッカー',
        exampleRomanji: 'sakkaa',
        exampleTranslation: 'soccer',
        emoji: '⚽',
    },
    {
        character: 'シ',
        romanji: 'SHI',
        example: 'シャワー',
        exampleRomanji: 'shawaa',
        exampleTranslation: 'shower',
        emoji: '🚿',
    },
    {
        character: 'ス',
        romanji: 'SU',
        example: 'スープ',
        exampleRomanji: 'suupu',
        exampleTranslation: 'soup',
        emoji: '🥣',
    },
    {
        character: 'セ',
        romanji: 'SE',
        example: 'セーター',
        exampleRomanji: 'seetaa',
        exampleTranslation: 'sweater',
        emoji: '🧥',
    },
    {
        character: 'ソ',
        romanji: 'SO',
        example: 'ソース',
        exampleRomanji: 'soosu',
        exampleTranslation: 'sauce',
        emoji: '🥫',
    },
    // T-row
    {
        character: 'タ',
        romanji: 'TA',
        example: 'タクシー',
        exampleRomanji: 'takushii',
        exampleTranslation: 'taxi',
        emoji: '🚕',
    },
    {
        character: 'チ',
        romanji: 'CHI',
        example: 'チーズ',
        exampleRomanji: 'chiizu',
        exampleTranslation: 'cheese',
        emoji: '🧀',
    },
    {
        character: 'ツ',
        romanji: 'TSU',
        example: 'ツアー',
        exampleRomanji: 'tsuaa',
        exampleTranslation: 'tour',
        emoji: '🗺️',
    },
    {
        character: 'テ',
        romanji: 'TE',
        example: 'テレビ',
        exampleRomanji: 'terebi',
        exampleTranslation: 'television',
        emoji: '📺',
    },
    {
        character: 'ト',
        romanji: 'TO',
        example: 'トマト',
        exampleRomanji: 'tomato',
        exampleTranslation: 'tomato',
        emoji: '🍅',
    },
    // N-row
    {
        character: 'ナ',
        romanji: 'NA',
        example: 'ナイフ',
        exampleRomanji: 'naifu',
        exampleTranslation: 'knife',
        emoji: '🔪',
    },
    {
        character: 'ニ',
        romanji: 'NI',
        example: 'ニュース',
        exampleRomanji: 'nyuusu',
        exampleTranslation: 'news',
        emoji: '📰',
    },
    {
        character: 'ヌ',
        romanji: 'NU',
        example: 'ヌードル',
        exampleRomanji: 'nuudoru',
        exampleTranslation: 'noodle',
        emoji: '🍜',
    },
    {
        character: 'ネ',
        romanji: 'NE',
        example: 'ネクタイ',
        exampleRomanji: 'nekutai',
        exampleTranslation: 'necktie',
        emoji: '👔',
    },
    {
        character: 'ノ',
        romanji: 'NO',
        example: 'ノート',
        exampleRomanji: 'nooto',
        exampleTranslation: 'notebook',
        emoji: '📓',
    },
    // H-row
    {
        character: 'ハ',
        romanji: 'HA',
        example: 'ハンバーガー',
        exampleRomanji: 'hanbaagaa',
        exampleTranslation: 'hamburger',
        emoji: '🍔',
    },
    {
        character: 'ヒ',
        romanji: 'HI',
        example: 'ヒーロー',
        exampleRomanji: 'hiiroo',
        exampleTranslation: 'hero',
        emoji: '🦸',
    },
    {
        character: 'フ',
        romanji: 'FU',
        example: 'フォーク',
        exampleRomanji: 'fooku',
        exampleTranslation: 'fork',
        emoji: '🍴',
    },
    {
        character: 'ヘ',
        romanji: 'HE',
        example: 'ヘリコプター',
        exampleRomanji: 'herikoputaa',
        exampleTranslation: 'helicopter',
        emoji: '🚁',
    },
    {
        character: 'ホ',
        romanji: 'HO',
        example: 'ホテル',
        exampleRomanji: 'hoteru',
        exampleTranslation: 'hotel',
        emoji: '🏨',
    },
    // M-row
    {
        character: 'マ',
        romanji: 'MA',
        example: 'マスク',
        exampleRomanji: 'masuku',
        exampleTranslation: 'mask',
        emoji: '😷',
    },
    {
        character: 'ミ',
        romanji: 'MI',
        example: 'ミルク',
        exampleRomanji: 'miruku',
        exampleTranslation: 'milk',
        emoji: '🥛',
    },
    {
        character: 'ム',
        romanji: 'MU',
        example: 'チーム',
        exampleRomanji: 'chiimu',
        exampleTranslation: 'team',
        emoji: '🤝',
    },
    {
        character: 'メ',
        romanji: 'ME',
        example: 'メール',
        exampleRomanji: 'meeru',
        exampleTranslation: 'email',
        emoji: '📧',
    },
    {
        character: 'モ',
        romanji: 'MO',
        example: 'メモ',
        exampleRomanji: 'memo',
        exampleTranslation: 'memo',
        emoji: '📝',
    },
    // Y-row
    {
        character: 'ヤ',
        romanji: 'YA',
        example: 'タイヤ',
        exampleRomanji: 'taiya',
        exampleTranslation: 'tire',
        emoji: '🛞',
    },
    {
        character: 'ユ',
        romanji: 'YU',
        example: 'ユーチューブ',
        exampleRomanji: 'yuuchuubu',
        exampleTranslation: 'YouTube',
        emoji: '▶️',
    },
    {
        character: 'ヨ',
        romanji: 'YO',
        example: 'ヨーグルト',
        exampleRomanji: 'yooguruto',
        exampleTranslation: 'yogurt',
        emoji: '🥣',
    },
    // R-row
    {
        character: 'ラ',
        romanji: 'RA',
        example: 'ラジオ',
        exampleRomanji: 'rajio',
        exampleTranslation: 'radio',
        emoji: '📻',
    },
    {
        character: 'リ',
        romanji: 'RI',
        example: 'リスト',
        exampleRomanji: 'risuto',
        exampleTranslation: 'list',
        emoji: '📋',
    },
    {
        character: 'ル',
        romanji: 'RU',
        example: 'ルール',
        exampleRomanji: 'ruuru',
        exampleTranslation: 'rule',
        emoji: '📏',
    },
    {
        character: 'レ',
        romanji: 'RE',
        example: 'レストラン',
        exampleRomanji: 'resutoran',
        exampleTranslation: 'restaurant',
        emoji: '🍽️',
    },
    {
        character: 'ロ',
        romanji: 'RO',
        example: 'ロボット',
        exampleRomanji: 'robotto',
        exampleTranslation: 'robot',
        emoji: '🤖',
    },
    // W-row
    {
        character: 'ワ',
        romanji: 'WA',
        example: 'ワイン',
        exampleRomanji: 'wain',
        exampleTranslation: 'wine',
        emoji: '🍷',
    },
    {
        character: 'ヲ',
        romanji: 'WO',
        example: 'ヲ',
        exampleRomanji: 'wo',
        exampleTranslation: 'object particle (rare in katakana)',
        emoji: '🔤',
    },
    // N
    {
        character: 'ン',
        romanji: 'N',
        example: 'パン',
        exampleRomanji: 'pan',
        exampleTranslation: 'bread',
        emoji: '🍞',
    },
];

export const dakutenHandakuten: KanaItem[] = [
    // Dakuten - G-row
    {
        character: 'ガ',
        romanji: 'GA',
        example: 'ガス',
        exampleRomanji: 'gasu',
        exampleTranslation: 'gas',
        emoji: '⛽',
    },
    {
        character: 'ギ',
        romanji: 'GI',
        example: 'ギター',
        exampleRomanji: 'gitaa',
        exampleTranslation: 'guitar',
        emoji: '🎸',
    },
    {
        character: 'グ',
        romanji: 'GU',
        example: 'グループ',
        exampleRomanji: 'guruupu',
        exampleTranslation: 'group',
        emoji: '👨‍👩‍👧‍👦',
    },
    {
        character: 'ゲ',
        romanji: 'GE',
        example: 'ゲーム',
        exampleRomanji: 'geemu',
        exampleTranslation: 'game',
        emoji: '🎮',
    },
    {
        character: 'ゴ',
        romanji: 'GO',
        example: 'ゴルフ',
        exampleRomanji: 'gorufu',
        exampleTranslation: 'golf',
        emoji: '⛳',
    },
    // Dakuten - Z-row
    {
        character: 'ザ',
        romanji: 'ZA',
        example: 'デザイン',
        exampleRomanji: 'dezain',
        exampleTranslation: 'design',
        emoji: '🎨',
    },
    {
        character: 'ジ',
        romanji: 'JI',
        example: 'ジーンズ',
        exampleRomanji: 'jiinzu',
        exampleTranslation: 'jeans',
        emoji: '👖',
    },
    {
        character: 'ズ',
        romanji: 'ZU',
        example: 'ズボン',
        exampleRomanji: 'zubon',
        exampleTranslation: 'trousers',
        emoji: '👖',
    },
    {
        character: 'ゼ',
        romanji: 'ZE',
        example: 'ゼロ',
        exampleRomanji: 'zero',
        exampleTranslation: 'zero',
        emoji: '0️⃣',
    },
    {
        character: 'ゾ',
        romanji: 'ZO',
        example: 'ゾンビ',
        exampleRomanji: 'zonbi',
        exampleTranslation: 'zombie',
        emoji: '🧟',
    },
    // Dakuten - D-row
    {
        character: 'ダ',
        romanji: 'DA',
        example: 'ダンス',
        exampleRomanji: 'dansu',
        exampleTranslation: 'dance',
        emoji: '💃',
    },
    {
        character: 'ヂ',
        romanji: 'JI',
        example: 'ラヂオ',
        exampleRomanji: 'rajio',
        exampleTranslation: 'radio (archaic spelling)',
        emoji: '📻',
    },
    {
        character: 'ヅ',
        romanji: 'ZU',
        example: 'ミヅキ',
        exampleRomanji: 'mizuki',
        exampleTranslation: 'Mizuki (name)',
        emoji: '🧑',
    },
    {
        character: 'デ',
        romanji: 'DE',
        example: 'デザート',
        exampleRomanji: 'dezaato',
        exampleTranslation: 'dessert',
        emoji: '🍮',
    },
    {
        character: 'ド',
        romanji: 'DO',
        example: 'ドア',
        exampleRomanji: 'doa',
        exampleTranslation: 'door',
        emoji: '🚪',
    },
    // Dakuten - B-row
    {
        character: 'バ',
        romanji: 'BA',
        example: 'バス',
        exampleRomanji: 'basu',
        exampleTranslation: 'bus',
        emoji: '🚌',
    },
    {
        character: 'ビ',
        romanji: 'BI',
        example: 'ビール',
        exampleRomanji: 'biiru',
        exampleTranslation: 'beer',
        emoji: '🍺',
    },
    {
        character: 'ブ',
        romanji: 'BU',
        example: 'ブーツ',
        exampleRomanji: 'buutsu',
        exampleTranslation: 'boots',
        emoji: '👢',
    },
    {
        character: 'ベ',
        romanji: 'BE',
        example: 'ベッド',
        exampleRomanji: 'beddo',
        exampleTranslation: 'bed',
        emoji: '🛏️',
    },
    {
        character: 'ボ',
        romanji: 'BO',
        example: 'ボール',
        exampleRomanji: 'booru',
        exampleTranslation: 'ball',
        emoji: '⚾',
    },
    // Handakuten - P-row
    {
        character: 'パ',
        romanji: 'PA',
        example: 'パーティー',
        exampleRomanji: 'paathii',
        exampleTranslation: 'party',
        emoji: '🎉',
    },
    {
        character: 'ピ',
        romanji: 'PI',
        example: 'ピアノ',
        exampleRomanji: 'piano',
        exampleTranslation: 'piano',
        emoji: '🎹',
    },
    {
        character: 'プ',
        romanji: 'PU',
        example: 'プール',
        exampleRomanji: 'puuru',
        exampleTranslation: 'pool',
        emoji: '🏊',
    },
    {
        character: 'ペ',
        romanji: 'PE',
        example: 'ペン',
        exampleRomanji: 'pen',
        exampleTranslation: 'pen',
        emoji: '🖊️',
    },
    {
        character: 'ポ',
        romanji: 'PO',
        example: 'ポスト',
        exampleRomanji: 'posuto',
        exampleTranslation: 'mailbox',
        emoji: '📮',
    },
];

export const yoon: KanaItem[] = [
    // K-yoon
    {
        character: 'キャ',
        romanji: 'KYA',
        example: 'キャンプ',
        exampleRomanji: 'kyanpu',
        exampleTranslation: 'camp',
        emoji: '🏕️',
    },
    {
        character: 'キュ',
        romanji: 'KYU',
        example: 'キューバ',
        exampleRomanji: 'kyuuba',
        exampleTranslation: 'Cuba',
        emoji: '🇨🇺',
    },
    {
        character: 'キョ',
        romanji: 'KYO',
        example: 'キョウリュウ',
        exampleRomanji: 'kyouryuu',
        exampleTranslation: 'dinosaur',
        emoji: '🦕',
    },
    // G-yoon
    {
        character: 'ギャ',
        romanji: 'GYA',
        example: 'ギャンブル',
        exampleRomanji: 'gyanburu',
        exampleTranslation: 'gamble',
        emoji: '🎲',
    },
    {
        character: 'ギュ',
        romanji: 'GYU',
        example: 'フィギュア',
        exampleRomanji: 'figyua',
        exampleTranslation: 'figure/figurine',
        emoji: '🧍',
    },
    {
        character: 'ギョ',
        romanji: 'GYO',
        example: 'サンギョプサル',
        exampleRomanji: 'sangyopusaru',
        exampleTranslation: 'samgyeopsal',
        emoji: '🥓',
    },
    // S-yoon
    {
        character: 'シャ',
        romanji: 'SHA',
        example: 'シャツ',
        exampleRomanji: 'shatsu',
        exampleTranslation: 'shirt',
        emoji: '👕',
    },
    {
        character: 'シュ',
        romanji: 'SHU',
        example: 'シュークリーム',
        exampleRomanji: 'shuukuriimu',
        exampleTranslation: 'cream puff',
        emoji: '🍮',
    },
    {
        character: 'ショ',
        romanji: 'SHO',
        example: 'ショッピング',
        exampleRomanji: 'shoppingu',
        exampleTranslation: 'shopping',
        emoji: '🛍️',
    },
    // J-yoon
    {
        character: 'ジャ',
        romanji: 'JA',
        example: 'ジャケット',
        exampleRomanji: 'jaketto',
        exampleTranslation: 'jacket',
        emoji: '🧥',
    },
    {
        character: 'ジュ',
        romanji: 'JU',
        example: 'ジュース',
        exampleRomanji: 'juusu',
        exampleTranslation: 'juice',
        emoji: '🧃',
    },
    {
        character: 'ジョ',
        romanji: 'JO',
        example: 'ジョギング',
        exampleRomanji: 'jogingu',
        exampleTranslation: 'jogging',
        emoji: '🏃',
    },
    // CH-yoon
    {
        character: 'チャ',
        romanji: 'CHA',
        example: 'チャンス',
        exampleRomanji: 'chansu',
        exampleTranslation: 'chance',
        emoji: '✨',
    },
    {
        character: 'チュ',
        romanji: 'CHU',
        example: 'チューリップ',
        exampleRomanji: 'chuurippu',
        exampleTranslation: 'tulip',
        emoji: '🌷',
    },
    {
        character: 'チョ',
        romanji: 'CHO',
        example: 'チョコレート',
        exampleRomanji: 'chokoreeto',
        exampleTranslation: 'chocolate',
        emoji: '🍫',
    },
    // D-yoon
    {
        character: 'ヂャ',
        romanji: 'JA',
        example: 'ヂャズ',
        exampleRomanji: 'jazu',
        exampleTranslation: 'jazz (historical katakana spelling)',
        emoji: '🎷',
    }, // rare — historical pre-1946 katakana
    {
        character: 'ヂュ',
        romanji: 'JU',
        example: 'ヂュラルミン',
        exampleRomanji: 'jurarumin',
        exampleTranslation: 'duralumin (historical katakana spelling)',
        emoji: '✈️',
    }, // rare — historical pre-1946 katakana
    {
        character: 'ヂョ',
        romanji: 'JO',
        example: 'ヂョコビッチ',
        exampleRomanji: 'jokobicchi',
        exampleTranslation: 'Djokovic (historical katakana rendering)',
        emoji: '🎾',
    }, // rare — historical pre-1946 katakana
    // N-yoon
    {
        character: 'ニャ',
        romanji: 'NYA',
        example: 'ニャー',
        exampleRomanji: 'nyaa',
        exampleTranslation: 'meow',
        emoji: '🐈',
    },
    {
        character: 'ニュ',
        romanji: 'NYU',
        example: 'ニューヨーク',
        exampleRomanji: 'nyuuyooku',
        exampleTranslation: 'New York',
        emoji: '🗽',
    },
    {
        character: 'ニョ',
        romanji: 'NYO',
        example: 'ニョッキ',
        exampleRomanji: 'nyokki',
        exampleTranslation: 'gnocchi',
        emoji: '🍝',
    },
    // H-yoon
    {
        character: 'ヒャ',
        romanji: 'HYA',
        example: 'ヒャッホー',
        exampleRomanji: 'hyahhoo',
        exampleTranslation: 'yahoo!',
        emoji: '😄',
    },
    {
        character: 'ヒュ',
        romanji: 'HYU',
        example: 'ヒューマン',
        exampleRomanji: 'hyuuman',
        exampleTranslation: 'human',
        emoji: '🧑',
    },
    {
        character: 'ヒョ',
        romanji: 'HYO',
        example: 'ヒョウ',
        exampleRomanji: 'hyou',
        exampleTranslation: 'leopard',
        emoji: '🐆',
    },
    // B-yoon
    {
        character: 'ビャ',
        romanji: 'BYA',
        example: 'ビャウィストク',
        exampleRomanji: 'byawisutoku',
        exampleTranslation: 'Białystok (city in Poland)',
        emoji: '🇵🇱',
    },
    {
        character: 'ビュ',
        romanji: 'BYU',
        example: 'ビューティー',
        exampleRomanji: 'byuutii',
        exampleTranslation: 'beauty',
        emoji: '💅',
    },
    {
        character: 'ビョ',
        romanji: 'BYO',
        example: 'ビョルン',
        exampleRomanji: 'byorun',
        exampleTranslation: 'Bjorn (name)',
        emoji: '🧑‍🦰',
    },
    // P-yoon
    {
        character: 'ピャ',
        romanji: 'PYA',
        example: 'ピャスト',
        exampleRomanji: 'pyasuto',
        exampleTranslation: 'Piast (Polish dynasty)',
        emoji: '👑',
    },
    {
        character: 'ピュ',
        romanji: 'PYU',
        example: 'コンピュータ',
        exampleRomanji: 'konpyuuta',
        exampleTranslation: 'computer',
        emoji: '💻',
    },
    {
        character: 'ピョ',
        romanji: 'PYO',
        example: 'ピョートル',
        exampleRomanji: 'pyootoru',
        exampleTranslation: 'Pyotr (name)',
        emoji: '🧑‍🔬',
    },
];

export const katakanaItems: KanaItem[] = [...gojuon, ...dakutenHandakuten, ...yoon];
