import { readFile } from 'node:fs/promises';
import path from 'node:path';
import type { Plugin } from 'vite';
// Relative import (not the `@/` alias) because vite.config.ts loads this file directly,
// and Vite's config loader does not apply tsconfig path mapping.
import { siteRoutes } from '../lib/routes-manifest';

/**
 * Fails the build when the router and `lib/routes-manifest.ts` disagree.
 *
 * Prerendering is driven entirely by the manifest (`crawlLinks` and
 * `autoStaticPathsDiscovery` are both off), so a route file that nobody added to the
 * manifest still compiles into the bundle but never gets an HTML file. It works when you
 * click to it and 404s on a direct visit or for a crawler — a failure that only shows up
 * in production. This turns that into a build error.
 */

const ROUTE_TREE = 'src/routeTree.gen.ts';
const MANIFEST = 'lib/routes-manifest.ts';

/** `/flashcards/` and `/flashcards` are the same page; compare one spelling. */
const normalize = (routePath: string): string =>
    routePath.length > 1 ? routePath.replace(/\/$/, '') : routePath;

const isDynamic = (routePath: string): boolean => routePath.includes('$');

/** `/hiragana/$character` matches `/hiragana/<anything without a slash>`. */
const toMatcher = (routePath: string): RegExp =>
    new RegExp(
        `^${normalize(routePath)
            .split('/')
            .map((segment) =>
                segment.startsWith('$') ? '[^/]+' : segment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
            )
            .join('/')}$`
    );

/**
 * Reads the `FileRoutesByFullPath` interface rather than the `path:` fields on each
 * route: a route nested under a layout parent declares its path relative to that parent
 * (`/$character`), and only this block spells out the full URL (`/kanji/$character`).
 */
async function readRouteTreePaths(root: string): Promise<string[]> {
    const source = await readFile(path.resolve(root, ROUTE_TREE), 'utf8');
    const block = source.match(/export interface FileRoutesByFullPath \{([\s\S]*?)\n\}/)?.[1];

    if (!block) {
        return [];
    }

    const paths = [...block.matchAll(/^\s*'([^']+)':/gm)].map((match) => match[1]);

    return [...new Set(paths.map(normalize))];
}

export function assertRoutesMatchManifest(): Plugin {
    return {
        name: 'assert-routes-match-manifest',
        // `post` so the route tree has been regenerated by the TanStack plugin first.
        enforce: 'post',
        async buildStart() {
            const root = process.cwd();
            let routePaths: string[];

            try {
                routePaths = await readRouteTreePaths(root);
            } catch {
                this.warn(`Could not read ${ROUTE_TREE}; skipping route/manifest check.`);
                return;
            }

            if (routePaths.length === 0) {
                this.warn(`No routes found in ${ROUTE_TREE}; skipping route/manifest check.`);
                return;
            }

            const manifestPaths = siteRoutes.map((route) => normalize(route.path));
            const manifestSet = new Set(manifestPaths);
            const problems: string[] = [];

            // 1. Every static route needs its own manifest entry, or it is never built.
            const unlisted = routePaths.filter((p) => !isDynamic(p) && !manifestSet.has(p));

            if (unlisted.length > 0) {
                problems.push(
                    `These routes exist in ${ROUTE_TREE} but are missing from ${MANIFEST}, ` +
                        `so no HTML is generated for them and they will 404 in production:\n` +
                        unlisted.map((p) => `    ${p}`).join('\n')
                );
            }

            // 2. A dynamic route is only useful if the manifest lists concrete paths for it.
            const uncovered = routePaths
                .filter(isDynamic)
                .filter((p) => !manifestPaths.some((entry) => toMatcher(p).test(entry)));

            if (uncovered.length > 0) {
                problems.push(
                    `These dynamic routes have no matching paths in ${MANIFEST}, ` +
                        `so none of their pages are generated:\n` +
                        uncovered.map((p) => `    ${p}`).join('\n')
                );
            }

            // 3. A manifest path with no route prerenders to the 404 page.
            const matchers = routePaths.map(toMatcher);
            const unmatched = manifestPaths.filter((entry) => !matchers.some((r) => r.test(entry)));

            if (unmatched.length > 0) {
                problems.push(
                    `These paths in ${MANIFEST} match no route in ${ROUTE_TREE}:\n` +
                        unmatched
                            .slice(0, 10)
                            .map((p) => `    ${p}`)
                            .join('\n') +
                        (unmatched.length > 10 ? `\n    ...and ${unmatched.length - 10} more` : '')
                );
            }

            if (problems.length > 0) {
                this.error(
                    `Routes and the site manifest are out of sync.\n\n${problems.join('\n\n')}\n\n` +
                        `Add or remove entries in ${MANIFEST} so it lists every page the site serves.`
                );
            }
        },
    };
}
