import { mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

import * as KanaStrokeOrder from '@/lib/kana-stroke-order';
import { hiraganaItems } from '@/lib/hiragana';
import { katakanaItems } from '@/lib/katakana';

type ParsedKanaStrokeSvg = KanaStrokeOrder.ParsedKanaStrokeSvg;

const ROOT_DIR = process.cwd();
const SOURCE_DIR = path.join(ROOT_DIR, 'public', 'kana-svgs');
const OUTPUT_DIR = path.join(ROOT_DIR, 'generated', 'kana-stroke-data');
const GENERATED_HEADER =
    '// This file is generated by scripts/generate-kana-stroke-data.ts. Do not edit manually.\n';

const getAttribute = (tag: string, attributeName: string): string | null => {
    const attributeMatch = tag.match(new RegExp(`\\b${attributeName}="([^"]*)"`, 'i'));

    return attributeMatch?.[1] ?? null;
};

const parseKanaSourceSvg = (svgMarkup: string, glyphCode: string): ParsedKanaStrokeSvg => {
    const viewBox = svgMarkup.match(/<svg\b[^>]*\bviewBox="([^"]+)"/i)?.[1];

    if (!viewBox) {
        throw new Error(`Missing viewBox for glyph ${glyphCode}.`);
    }

    const paths = Array.from(svgMarkup.matchAll(/<path\b[^>]*?(?:\/>|><\/path>)/gi))
        .map(([tag]) => ({
            id: getAttribute(tag, 'id') ?? '',
            d: getAttribute(tag, 'd') ?? '',
        }))
        .filter((pathData) => pathData.id.length > 0 && pathData.d.length > 0);

    if (paths.length === 0) {
        throw new Error(`No stroke paths found for glyph ${glyphCode}.`);
    }

    const numbers = Array.from(svgMarkup.matchAll(/<text\b[^>]*>[\s\S]*?<\/text>/gi)).map(
        ([tag]) => ({
            value: tag.replace(/<[^>]+>/g, '').trim(),
            transform: getAttribute(tag, 'transform') ?? '',
        })
    );

    return {
        viewBox,
        paths,
        numbers,
    };
};

const formatRegistryModule = (glyphEntries: Array<[string, ParsedKanaStrokeSvg]>) => {
    const entries = glyphEntries
        .map(
            ([glyphCode, data]) =>
                `    '${glyphCode}': ${JSON.stringify(data, null, 4).replace(/\n/g, '\n    ')},`
        )
        .join('\n');

    return `${GENERATED_HEADER}
import type { ParsedKanaStrokeSvg } from '@/lib/kana-stroke-order';

export const kanaStrokeRegistry: Record<string, ParsedKanaStrokeSvg> = {
${entries}
};
`;
};

const getUsedGlyphCodes = (): string[] =>
    Array.from(
        new Set(
            [...hiraganaItems, ...katakanaItems].flatMap((item) =>
                KanaStrokeOrder.splitKanaGlyphs(item.character).map((character) =>
                    KanaStrokeOrder.getKanaGlyphCode(character)
                )
            )
        )
    ).sort();

const removeStaleGeneratedModules = async () => {
    const existingEntries = await readdir(OUTPUT_DIR, { withFileTypes: true }).catch(() => []);

    await Promise.all(
        existingEntries
            .filter((entry) => {
                if (!entry.isFile() || !entry.name.endsWith('.ts')) {
                    return false;
                }

                return entry.name !== 'index.ts';
            })
            .map((entry) => rm(path.join(OUTPUT_DIR, entry.name)))
    );
};

const main = async () => {
    const glyphCodes = getUsedGlyphCodes();
    const glyphEntries: Array<[string, ParsedKanaStrokeSvg]> = [];

    await mkdir(OUTPUT_DIR, { recursive: true });

    for (const glyphCode of glyphCodes) {
        const sourcePath = path.join(SOURCE_DIR, `${glyphCode}.svg`);
        const svgMarkup = await readFile(sourcePath, 'utf8').catch(() => null);

        if (svgMarkup === null) {
            throw new Error(`Missing source SVG for glyph ${glyphCode}.`);
        }

        const parsedSvg = parseKanaSourceSvg(svgMarkup, glyphCode);
        glyphEntries.push([glyphCode, parsedSvg]);
    }

    const indexPath = path.join(OUTPUT_DIR, 'index.ts');
    const tempIndexPath = path.join(
        OUTPUT_DIR,
        `index.ts.${process.pid}.${Date.now()}.tmp`
    );

    await writeFile(tempIndexPath, formatRegistryModule(glyphEntries));
    await rename(tempIndexPath, indexPath);
    await removeStaleGeneratedModules();
    process.stdout.write(`Generated kana stroke data for ${glyphCodes.length} glyphs.\n`);
};

void main().catch((error: unknown) => {
    process.stderr.write(`${String(error)}\n`);
    process.exitCode = 1;
});
