/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HiraganaCharacterRouteImport } from './routes/hiragana/$character'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HiraganaCharacterRoute = HiraganaCharacterRouteImport.update({
  id: '/hiragana/$character',
  path: '/hiragana/$character',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hiragana/$character': typeof HiraganaCharacterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hiragana/$character': typeof HiraganaCharacterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hiragana/$character': typeof HiraganaCharacterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hiragana/$character'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hiragana/$character'
  id: '__root__' | '/' | '/hiragana/$character'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HiraganaCharacterRoute: typeof HiraganaCharacterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiragana/$character': {
      id: '/hiragana/$character'
      path: '/hiragana/$character'
      fullPath: '/hiragana/$character'
      preLoaderRoute: typeof HiraganaCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HiraganaCharacterRoute: HiraganaCharacterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
